# Generated by Django 4.1.1 on 2023-02-05 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('chat_id', models.SmallIntegerField(verbose_name='ID чата')),
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True, verbose_name='Имя пользователя @')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Фотография')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='api.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='api.user')),
            ],
            options={
                'verbose_name': 'Валентинка',
                'verbose_name_plural': 'Валентинки',
            },
        ),
    ]
