# Generated by Django 4.1.1 on 2023-02-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_letter_receiver_alter_letter_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=64, verbose_name='Имя и фамилия'),
            preserve_default=False,
        ),
    ]
